### ISSUE TITLE
error building CIA.

### ISSUE THREAD

**Issue by Timtendo12** [mkst/sm64-port#64]
`Timsl@LAPTOP-STVUE3H6 MSYS ~/sm64-port
$ make VERSION=us cia
make: gcc: No such file or directory
make: *** [Makefile:66: n64graphics] Error 127
Traceback (most recent call last):
  File "/home/Timsl/sm64-port/./extract_assets.py", line 292, in <module>
    main()
  File "/home/Timsl/sm64-port/./extract_assets.py", line 162, in main
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:179: *** Failed to extract assets.  Stop.
`

full history

https://pastebin.com/sP4c6fzY

**Comment by mkst** [comment]
Looks like you're using MSYS not MINGW64...
